_BASE_: "coco_R_50_FPN_CONV_1x_moco_adam.yaml"
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  ROI_HEADS:
    NUM_CLASSES: 9
DATASETS:
  COCO_DIR: "../../datasets/coco"
  TRAIN: ("coco_2017_train_subset",)
  TEST: ("coco_2017_val_subset",)
SOLVER:
  NUM_EPOCHS: 12
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 500
  LR_DECAY: 1.0
TEST:
  EVAL_PERIOD: 500
